# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d9ef41cd07695439a667c408af54dc9410e1a4255e29ee7a680c8765170773691f0deaaa174700968c17e327491d93d5b8069e60c71df7c89beb4997b8a831

test:
  secret_key_base: bfd7a00ddd328d2f13a6810e71c40af6d18973fc5672c8d0bee412a1eb614a4c11e34b065d626e7d347d9433bc9a537b308ebe547fd857cbb7f1cb5a9b04ebea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
